### ISSUE TITLE
请教一下，关于博客标题的字体

### ISSUE THREAD

**Issue by zouyifeng** [jigsawye/jigsawye.github.io#1]
你好，我在网上留意到你的博客，发现文章的标题的中文字体很漂亮，但又和主题的demo有所区别。自己摸索了下没有什么结果，所以想请教下如何设置这字体呢？ 谢谢~

你博客上的字体
![image](https://user-images.githubusercontent.com/22537660/30461239-71471e16-99ef-11e7-887e-971d4ba9d6af.png)

demo博客的字体
![image](https://user-images.githubusercontent.com/22537660/30461244-825439aa-99ef-11e7-8805-fad1ba0e59ee.png)

[博客demo地址](http://pinggod.com/)

**Comment by jigsawye** [comment]
hi @zouyifeng 

不知道你是不是用 windows 系統，因為我的 `font-family` 有針對 windows 加上 `微軟正黑體`。

Source:

https://github.com/pinggod/hexo-theme-apollo/blob/master/source/scss/_partial/base.scss#L17

而我的是：

```css
body {
  // ...
  font-family: 'sourcesanspro', 'Helvetica Neue', Arial, sans-serif, '微軟正黑體';
}
```

你也可以替換成你需要的字型，接著在 `theme/apollo` 內執行 `gulp sass` 即可
